version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: osrs-price-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: osrs_prices
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Uncomment to run the API alongside the database
  # api:
  #   build: .
  #   container_name: osrs-price-api
  #   environment:
  #     DATABASE_URL: postgresql://postgres:postgres@postgres:5432/osrs_prices?sslmode=disable
  #     PORT: 8080
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

volumes:
  postgres_data: