version: '3.8'

services:
  # OSRS Price API (connecting to external database)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: osrs-price-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    # Environment variables from .env file are loaded automatically
    # Or you can specify them here:
    # environment:
    #   DATABASE_URL: postgresql://user:password@external-host:5432/osrs_prices
    #   PORT: 8080
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - osrs-network

networks:
  osrs-network:
    driver: bridge